services:
  evently.api:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.Api
    build:
      context: .
      dockerfile: src/api/Evently.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evently
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    postgres-data:

    
  
